name: CI
 
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
 
jobs:
  frontend:
    name: Frontend - Lint & Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: npm run build
 
  backend:
    name: Backend - Lint & Build
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      - run: npm ci     
      - run: npx prisma db push
      #- run: npm run build
  pruebas:
    name: Pruebas unitarias y cobertura
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    #defaults:
    #  run:
    #    working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      #- run: npm ci
      #- run: npx vitest run --coverage
      # Frontend dependencies
      - run: npm ci
        working-directory: ./
      - run: npm ci
        working-directory: ./backend  
      - run: npx prisma generate
        working-directory: ./backend  
      - run: npx vitest run --coverage
        working-directory: ./
        
 
  e2e:
    name: Pruebas E2E
    runs-on: ubuntu-latest
    env:
      VITE_API_URL: ${{ secrets.VITE_API_URL }}
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npx playwright install --with-deps chromium
      - run: npx playwright test

  migraciones:
    name: Migraciones y Seeds
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./backend
    env:
      DATABASE_URL: postgresql://testuser:testpass@localhost:5432/testdb
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: '20'
            cache: 'npm'
      - run: npm ci
      - run: npx prisma migrate deploy